name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build sysroot tarball
        run: make

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: vscode-sysroot
        path: toolchain/vscode-sysroot-*.tgz
